package Amazon::MWS::Enumeration::FeedType;

use strict;
use warnings;

use base qw(Amazon::MWS::Enumeration);

__PACKAGE__->define qw(
    _POST_PRODUCT_DATA_
    _POST_PRODUCT_RELATIONSHIP_DATA_
    _POST_ITEM_DATA_
    _POST_PRODUCT_OVERRIDES_DATA_
    _POST_PRODUCT_IMAGE_DATA_
    _POST_PRODUCT_PRICING_DATA_
    _POST_INVENTORY_AVAILABILITY_DATA_
    _POST_ORDER_ACKNOWLEDGEMENT_DATA_
    _POST_ORDER_FULFILLMENT_DATA_
    _POST_PAYMENT_ADJUSTMENT_DATA_
    _POST_FLAT_FILE_LISTINGS_DATA_
    _POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA_
    _POST_FLAT_FILE_FULFILLMENT_DATA_
    _POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA_
    _POST_FLAT_FILE_INVLOADER_DATA_
);

1;
