package Amazon::MWS::Enumeration::ReportType;

use strict;
use warnings;

use base qw(Amazon::MWS::Enumeration);

__PACKAGE__->define qw(
    _GET_FLAT_FILE_OPEN_LISTINGS_DATA_
    _GET_MERCHANT_LISTINGS_DATA_
    _GET_MERCHANT_LISTINGS_DATA_LITE_
    _GET_MERCHANT_LISTINGS_DATA_LITER_
    _GET_MERCHANT_CANCELLED_LISTINGS_DATA_
    _GET_NEMO_MERCHANT_LISTINGS_DATA_
    _GET_AFN_INVENTORY_DATA_
    _GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_
    _GET_ORDERS_DATA_
    _GET_FLAT_FILE_ORDER_REPORT_DATA_
    _GET_FLAT_FILE_ORDERS_DATA_
    _GET_CONVERGED_FLAT_FILE_ORDER_REPORT_DATA_
);

1;
